### ISSUE TITLE
Question about recording, saving, and analyzing data

### ISSUE THREAD

**Issue by Jmeng3** [MattNolanLab/pySPAD#3]
Hi Kurtulus,

Thank you again for your earlier help. I saved a recording of 1 block with 10,000 bitplanes. However, it was unclear when the recording finished. In the matlab GUI, a box appears saying that the recording is complete. Could such a 'finished' alert be implemented in the python GUI? 

I wanted to look at the trace using Yifang's SPADreadBin.py script but the code looks like it is geared towards .bin files collected using the Matlab GUI. Is this so? Is there another script that handles .bin files generated using the python GUI? If it is easier, should I reach out to Yifang and ask her which script she uses to plot the trace python GUI generated .bin files? Thank you!

Best,
Julia

**Comment by kurtulusbulus** [comment]
Hi Julia, 

Thank you for bringing this up. 

I have noted down your suggestion, this will be implemented in the next update! While we are working on this, you can see when the recording started and finished on the terminal window that you run the GUI (black screen where you promt run.py). 

For analysing the trace, we are working on this these days. The pipeline will be out in a few days. In the meantime, I will write a quick script which shows you how to analyse the data. I will send the script over e-mail in a few hours. 

Sorry for inconvenience this might cause. 

Best, 

Kurtulus

**Comment by Jmeng3** [comment]
Hi Kurtulus,

Thank you! Absolutely, no worries!

Best,
Julia

**Comment by Jmeng3** [comment]
Another thought for future implementation...

Ultimately, I will want to trigger the SPAD via a digitizer. This is what Tian et al 2022 did. Does the current python GUI code allow for the .bit file needed for a trigger to be sent to the FPGA? If I understand correctly, to run the sensor spcimager_Top.bit is sent whereas to trigger the sensor through something like a digitizer, spcimager_Top_trigger.bit is sent (see https://github.com/MattNolanLab/SPAD_in_vivo/blob/main/SPCIMAGER_AA_USB3_UserGuide.md ).

Best,
Julia

**Comment by kurtulusbulus** [comment]
Hi Julia, 

That is another feature we are working on now! It will be out next week. So, you will be able to use pySPAD with trigger mode. 

For analysis trace, I have just noticed that you have access to SPADReadBin.py file on our lab repo. You can use that script to analyse the .bin file, but when you call the function `SPADReadBin()`, you do the following: 

`SPADReadBin(filename, pyGUI=True)`

After that the rest of the script should work fine. 

Let us know if it does not work for you. 

Best, 

Kurtulus

**Comment by Jmeng3** [comment]
Hi Kurtulus,

The script works for me! Thank you! 

Best,
Julia
